### ISSUE TITLE
Column showing if entry has OTP or not

### ISSUE THREAD

**Issue by alystair** [KeeTrayTOTP/KeeTrayTOTP#120]
The current TOTP column reveals the OTP - and the asterisk option makes every entry contain them.

I'd like it if there was a column that simply shows a checkmark or equiv. if the entry contains a valid working OTP, this way the title of the entry doesn't necessarily have to include 'OTP' in it for quick reference.

Wished there was one for notes as well but that's beyond the scope of this project :D

**Comment by robinvanpoppel** [comment]
Linking this to #27, because I'm uncertain what to do with the functionality of the current column. 
I think this functionality makes sense. I'm just not sure not whether to add an extra column or replacing the existing functionality.

**Comment by alystair** [comment]
I'm not a fan of the current column, I like OTPs being kept as private as possible - although I feel an alternative should be setup, possibly via a 'Reveal OTP' menu option to go along with the current 'Show QR' option - would just pop up the currently selected entry OTP with timer.

**Comment by robinvanpoppel** [comment]
@alystair , in #123 I've added a new column to show the current status instead of the actual code. The old column is also still there. Attached to the [build](https://github.com/KeeTrayTOTP/KeeTrayTOTP/actions/runs/80523668) there's a plgx artifact, if you want to check that out :)

**Comment by robinvanpoppel** [comment]
This is currently in master (so any development will contain it). Will prepare a release somewhere later this week, that also contains it.

**Comment by alystair** [comment]
Finally tried it - Robin could you change it from a language specific string to a simple ✅ checkmark if enabled or ❌ cross if badly configured?
