### ISSUE TITLE
Not working under Windows 7 64 bit KeePass 2.44

### ISSUE THREAD

**Issue by DavidBitSource** [KeeTrayTOTP/KeeTrayTOTP#124]
Since 0.102 it stopped working under KeePass 2.44 and Win 7 64bit. There is just an incompatibility note when launching KeePass.

**Comment by robinvanpoppel** [comment]
That's a bummer. I do not have a windows 7 installation lying around, but don't know of a reason that shouldn't work anymore. Let's find out what is going on.

Could you run keepass with `--debug` and paste the text, log files, and/or a screenshot of the incompatibility error message in this issue?

**Comment by dannoe** [comment]
I can reproduce it on a win7 vm. Currently working on a fix.

**Comment by dannoe** [comment]
Unfortunately this is not so easy to fix completely. It looks like your .NET Framework version is too old. The plugin is currently targeting the .NET Framework 4.5. and prior. 

I could push it down to .NET Framework 4.0 with #125. 
Can you please try out the artifact (see https://github.com/KeeTrayTOTP/KeeTrayTOTP/actions/runs/81589530)
If this is not working, you have to install a newer version of the .NET framework. (at least 4.0)

**Comment by DavidBitSource** [comment]
Obviously it was not so bad after all, it works again!
