### ISSUE TITLE
[Suggestion] Auto set settings to "30;6" if just have "TOTP Seed" string field

### ISSUE THREAD

**Issue by Myuki** [KeeTrayTOTP/KeeTrayTOTP#147]
If I already have some TOTP seeds in entrys' string field before use KeeTrayTOTP. It is tiresome to add "TOTP Settings" string field in ever entry.

At meantime, most of the consumer TOTP's use 30s and 6 digits. In this situation, add a "TOTP Settings" string field is unnecessary. By this way, it can use just 1 string field "TOTP Seed" to store in entry.

**Comment by robinvanpoppel** [comment]
Thanks for this suggestion: I'll take a look :)

**Comment by robinvanpoppel** [comment]
@Myuki, this was just merged to master and is available in the latest [development build](https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases/tag/latest) if you'd like to check it out.
