### ISSUE TITLE
Add a context menu button to copy TOTP w/ Shortcut

### ISSUE THREAD

**Issue by bastolino** [KeeTrayTOTP/KeeTrayTOTP#156]
Hey,
at first - thanks to you for continuing that plugin! I used the original one for years but now I just switched over :)
Probably just a small thing: the original Plugin hat a button on a context menu to copy the totp, just next to copy user and copy password
(see [https://a.fsdn.com/con/app/proj/traytotp-kp2/screenshots/ContextMenu.png/max/max/1](https://a.fsdn.com/con/app/proj/traytotp-kp2/screenshots/ContextMenu.png/max/max/1))

Is there a specific reason why you gave that up? Especially the Ctrl+T was used a lot. Maybe you have a look at it and re-implement it?

Thanks a lot!
Best wishes

**Comment by robinvanpoppel** [comment]
Hi @bastolino, that option should still be there, but it has moved. Plugins that offer multiple actions on the context menu need to provide them via a submenu since Keepass 2.42 (See also #49, #36 ). The action should still be available in a submenu like this:

![image](https://user-images.githubusercontent.com/5755736/81492851-a0961d00-929b-11ea-9938-2876b897fabe.png)

Let me know if you're able to find it there. Also the shortcut `Ctrl+T` should still work.

**Comment by bastolino** [comment]
Hi @robinvanpoppel 
yes, this sub-menu is existent but those shortcuts are not available for me:
![Unbenannt](https://user-images.githubusercontent.com/4018936/81495801-4012da00-92b3-11ea-8173-e5590e68f30d.png)
Also trying the Ctrl+T did not copy the TOTP into clipboard.
So I guess it's rather a bug as the shortcut does not work than (what I thought at the beginning) a feature request. Are there any Logfiles or so I can share? I have Keepass 2.44 on an Ubuntu 20.04 (Gnome 3.36), all available patches applied.

**Comment by dannoe** [comment]
This is a bug in mono. We are using an overloaded constructor for assigning the shortcuts and the shortcut parameter in this constructor is not handled at all in the current mono runtime. see ([ToolStripMenuItem.cs of mono/mono](https://github.com/mono/mono/blob/169a842f4e913608b17a1e5f38bcb635063b8dc8/mcs/class/System.Windows.Forms/System.Windows.Forms/ToolStripMenuItem.cs#L83))

I released a fix for this in PR #158 and tested it on Ubuntu 20.04. with KeePass **2.45**
If this is PR is review and merged you can download the latest development build and it should work.

**Comment by robinvanpoppel** [comment]
Haha no, not at all @dannoe. When i assigned it I was not aware that it had to do with mono. Thanks for looking into it and providing a fix.

**Comment by bastolino** [comment]
Hey guys,
thanks for that awesome work!
