### ISSUE TITLE
New tray menu on multimonitor systems

### ISSUE THREAD

**Issue by EvvL** [KeeTrayTOTP/KeeTrayTOTP#160]
The new sub menu for the tray shows up on display 1 no matter which display the taskbar is actually on. 

I have three monitors on this system but I only have my taskbar showing on monitor 2. When I mouse over the Tray TOTP Plugin menu the new sub menu pops up where it should be on display 1 if the taskbar was over there.

**Comment by dannoe** [comment]
What OS are you using?
Do you have your taskbar on the bottom of the screen?

**Comment by EvvL** [comment]
I'm using windows 10. Yes I have the taskbar on the bottom of display 2 but not on display 1. Could it be that I have display 1 set below display 2?

**Comment by dannoe** [comment]
Yes, this was the missing information 😄 I can reproduce it.
Fix is coming.

**Comment by dannoe** [comment]
Can you test if this works with the [latest development build](https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases/tag/latest)?

**Comment by EvvL** [comment]
my one of my screens is smaller than the other too. That may play into this. I've attached a screenshot of what I'm seeing.
![screens](https://user-images.githubusercontent.com/39972602/82088723-1d176a00-96a7-11ea-8085-af76da4f90d3.png)

**Comment by EvvL** [comment]
Doing some quick testing, the issue only occurs when the taskbar is on the top monitor on the bottom or the right. When I move it to the top or left it works fine. 

I also hooked up a third monitor and placed it to the right of the top monitor in the display view, and all four positions work fine there.

**Comment by EvvL** [comment]
Sorry about spamming this bug with info. 

It doesn't seem to have to do with the size of the displays but the fact they're stacked vertically. When I take the new monitor 3 (same size as monitor 2) and place it above monitor 2. Putting the taskbar on the bottom of 3 causes the menu to display on the monitor below it (monitor 2). Just like monitor 2's menu displays on monitor 1.

**Comment by dannoe** [comment]
The bug is very related to this: https://stackoverflow.com/questions/26587843/prevent-toolstripmenuitems-from-jumping-to-second-screen/49626530#49626530
We are already using an workaround for this: https://github.com/KeeTrayTOTP/KeeTrayTOTP/blob/6302156d5a78e38d07003d3000efcdd23d4a5c9e/KeeTrayTOTP/Helpers/MenuItemHelper.cs#L9-L13

But, this has to be extended to calculate the height of the dropdown menu and apply one of these ToolStripDropDownDirection if the menu collides with the screen bounds.
- AboveRight
- AboveLeft
- BelowLeft
- BelowRight

It's pretty late for me, so I'm not going to fix this today.

**Comment by EvvL** [comment]
I just hit on something. I was looking and I have a looooot of totp keys, like it hits to top on the smaller screen. So I loaded a database with just a few keys and it works fine. Looking at the code I might be hitting `calculatedY = screenHeight - _controlSize.Height;` in CalculateY(...)

**Comment by dannoe** [comment]
The code from the pull request addresses another bug. It only calculates the opening position for the main contextmenu, not the sub menus.
The screenshots in #161 shows that I wasn't using the correct setup for fixing _your_ bug. My taskbar was on the TOP of the bottom screen.

**Comment by dannoe** [comment]
> 
> 
> The bug is very related to this: https://stackoverflow.com/questions/26587843/prevent-toolstripmenuitems-from-jumping-to-second-screen/49626530#49626530
> We are already using a workaround for this:
> 
> https://github.com/KeeTrayTOTP/KeeTrayTOTP/blob/6302156d5a78e38d07003d3000efcdd23d4a5c9e/KeeTrayTOTP/Helpers/MenuItemHelper.cs#L9-L13
> 
> But, this has to be extended to calculate the height of the dropdown menu and apply one of these ToolStripDropDownDirection if the menu collides with the screen bounds.
> 
>     * AboveRight
> 
>     * AboveLeft
> 
>     * BelowLeft
> 
>     * BelowRight
> 
> 
> It's pretty late for me, so I'm not going to fix this today.

Did not use this approach, as it looked awful.
Instead I am now checking if the dropdown was opened on another screen as the parent menu item. 
If this is the case, I am moving the menu up with its own height as y-offset.

This cost me quite some time, but I am now best friends with this little guy: [ToolStripMenuItem.cs](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ToolStripMenuItem.cs) 😄

**Comment by dannoe** [comment]
@EvvL Is this fixed for you with the [latest development build](https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases/tag/latest)?

**Comment by EvvL** [comment]
Yup, working now. Thanks.
