### ISSUE TITLE
Entries unsorted in new tray menu

### ISSUE THREAD

**Issue by Steltek** [KeeTrayTOTP/KeeTrayTOTP#167]
Not sure when the new sub-menu in the tray was introduced, but ever since getting it, I've noticed that all my TOTP entries are unsorted (used to be sorted alphabetically). This makes it near impossible to find anything in the very long list:

![2020-05-17 19_42_52-](https://user-images.githubusercontent.com/1315116/82155652-c3fe3080-9876-11ea-81ee-f2643d39d670.png)

Keepass: 2.45
KeeTrayTOTP: 0.106

**Comment by robinvanpoppel** [comment]
We did rework some of that code and added some filters so that could be the case. It would be good if the order is predictable.
