### ISSUE TITLE
I hope KeeTrayTOTP on the tray can be color-coded, because similar accounts are difficult to choose

### ISSUE THREAD

**Issue by vipei** [KeeTrayTOTP/KeeTrayTOTP#176]
I hope KeeTrayTOTP on the tray can be color-coded, because similar accounts are difficult to choose

**Comment by robinvanpoppel** [comment]
@vipei: I'm not fully sure if I understand you correctly. 

Do you run multiple instances of KeePass? KeePass is able to load multiple databases in a single instance as well, and these databases can be colour coded.

Database tabs on top:
![image](https://user-images.githubusercontent.com/5755736/89637047-e5851c00-d8a9-11ea-916b-50cec69ed6bf.png)

Submenu of KeeTrayToTp where the test.kdbx has a colour configured.
![image](https://user-images.githubusercontent.com/5755736/89636953-bbcbf500-d8a9-11ea-9047-7b9ea0e45da1.png)

**Comment by vipei** [comment]
> @vipe我不完全确定我是否正确地理解了你。
> 
> 您运行多个KeePass实例吗？KeePass还可以在一个实例中加载多个数据库，并且可以对这些数据库进行彩色编码。
> 
> 顶部的数据库选项卡：
> ![image](https://user-images.githubusercontent.com/5755736/89637047-e5851c00-d8a9-11ea-916b-50cec69ed6bf.png)
> 
> KeeTrayToTp的子菜单，其中test.kdbx配置了颜色。
> ![image](https://user-images.githubusercontent.com/5755736/89636953-bbcbf500-d8a9-11ea-9047-7b9ea0e45da1.png)






> @vipe我不完全确定我是否正确地理解了你。
> 
> 您运行多个KeePass实例吗？KeePass还可以在一个实例中加载多个数据库，并且可以对这些数据库进行彩色编码。
> 
> 顶部的数据库选项卡：
> ![image](https://user-images.githubusercontent.com/5755736/89637047-e5851c00-d8a9-11ea-916b-50cec69ed6bf.png)
> 
> KeeTrayToTp的子菜单，其中test.kdbx配置了颜色。
> ![image](https://user-images.githubusercontent.com/5755736/89636953-bbcbf500-d8a9-11ea-9047-7b9ea0e45da1.png)


I don't speak English. I use translation software to describe things. There are usually only a few accounts. It is difficult to choose when the accounts are very similar.  If you distinguish by color, you will quickly make a choice
![1](https://user-images.githubusercontent.com/49584327/92118222-c2a64300-ee28-11ea-8d9e-5698b43283ce.png)

**Comment by vipei** [comment]
> @VIPE我不完全确定我是否正确地理解了你.
> 
> 您运行多个Keepass实例吗？基帕斯还可以在一个实例中加载多个数据库，并且可以对这些数据库进行彩色编码。
> 
> 顶部的数据库选项卡：
> ![image](https://user-images.githubusercontent.com/5755736/89637047-e5851c00-d8a9-11ea-916b-50cec69ed6bf.png)
> 
> KeeTrayToTp的子菜单，其中test.kdbx配置了颜色.
> ![image](https://user-images.githubusercontent.com/5755736/89636953-bbcbf500-d8a9-11ea-9047-7b9ea0e45da1.png)

![2](https://user-images.githubusercontent.com/49584327/92119392-4f9dcc00-ee2a-11ea-9da2-78a8389fcc61.png)

**Comment by dannoe** [comment]
You have to download the development build of KeeTrayTOTP to be able to use this feature. 
see here: [[Releases]](https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases) [[Direct download link]](https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases/download/latest/KeeTrayTOTP.plgx)

![grafik](https://user-images.githubusercontent.com/7450586/92128644-206b6880-edf2-11ea-93f3-d259734bfb1c.png)

**Comment by vipei** [comment]
> 您必须下载KeeTrayTOTP的开发构建，才能使用此功能。
> 见这里：[[释放]](https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases) [[直接下载连结]](https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases/download/latest/KeeTrayTOTP.plgx)
> 
> ![grafik](https://user-images.githubusercontent.com/7450586/92128644-206b6880-edf2-11ea-93f3-d259734bfb1c.png)

very good, thank you

**Comment by robinvanpoppel** [comment]
Thanks @dannoe, I'll craft a new official release shortly.

**Comment by jon-f-novastor** [comment]
Thanks for this one, it works well.
