### ISSUE TITLE
please delete, I reported an issue with the wrong plugin (not KeeTrayTOTP)

### ISSUE THREAD

**Issue by jon-f-novastor** [KeeTrayTOTP/KeeTrayTOTP#182]
**Please delete this post, I reported an issue with the wrong plugin (not KeeTrayTOTP).**

.
.
.

Using KSSimpleBackup v1.3, if the option '**Backup database when it's being closed or when the KeePass application is being closed**' is **disabled**, it still saves the database when the database is being locked ('Lock Workspace' function).  With that option disabled, it should only save either when the database is being closed or the app is being closed instead.  If I turn off that option and lock the database, it does not save so I know KeePass v2.4.5 is not attempting that save and KSSimpleBackup v1.3 is doing it.  It does not seem to matter what combination of options I'm using, if this option is unchecked it will always save the database when only locking the database either manually using 'Lock Workspace' function, or automatically based on the auto-lock timer option value in KeePass v2.4.5.  See here for the option text in KSSimpleBackup v1.3:

![image](https://user-images.githubusercontent.com/50121594/91597928-1640fa00-e91a-11ea-8f86-13f1ce5f300a.png)

Can there be an option / method of using KSSimpleBackup where it only saves the database when the database is being closed or the app is being exited from (or when the manual 'Backup Database now!' menu item is clicked)?  That would be in addition to the 'Backup Database now!' function via the plugin menu.  Thanks in advance.

**Comment by dannoe** [comment]
This is the repository for the [KeeTrayTOTP](https://keepass.info/plugins.html#keetraytotp) plugin. 
You are probably looking for this repo: https://github.com/marvinweber/KPSimpleBackup

**Comment by jon-f-novastor** [comment]
> This is the repository for the [KeeTrayTOTP](https://keepass.info/plugins.html#keetraytotp) plugin.
> You are probably looking for this repo: https://github.com/marvinweber/KPSimpleBackup

So sorry, you are correct I reported the issue with KPSimpleBackup and not KeeTrayTOTP by mistake (too may browser tabs open currently to github!).  I just posted it over in the other repository as an issue: https://github.com/marvinweber/KPSimpleBackup/issues.  I have edited the title of this current post to say to delete it.  Thank you.

**Comment by jon-f-novastor** [comment]
Please delete this post, I reported an issue with the wrong plugin (not KeeTrayTOTP).
