### ISSUE TITLE
phone app compatibility

### ISSUE THREAD

**Issue by alexis26** [KeeTrayTOTP/KeeTrayTOTP#189]
hi,
can we use bases containing OTP codes (generated with KeeTrayTOTP) with keepass versions for phone, like KeePassDroid, keepass2android... ?
is it compatible?
thanks

**Comment by dannoe** [comment]
I am not sure about KeePassDroid, but [KeePass2Android](https://github.com/PhilippC/keepass2android) is TOTP compatible.
