### ISSUE TITLE
Bug: Help shows whenever KeePass ist started

### ISSUE THREAD

**Issue by dbartholomae** [KeeTrayTOTP/KeeTrayTOTP#195]
Hi there!

I'm running into the following bug (or maybe just me not finding the setting): On every start of KeePass, before logging in, the KeeTrayTOTP help window shows up.
Is this intentional? If not, how can I help with debugging?

**Comment by robinvanpoppel** [comment]
Hi @dbartholomae, this is not intentional and reminds me of issue #18. Can you take a look there?

**Comment by dbartholomae** [comment]
Thanks! Today the bug did not reappear, and the setting is set. I will monitor the situation and reopen the issue with more information when it reappears.
