### ISSUE TITLE
Question: How to upgrade from TrayTOTP to KeeTrayTOTP?

### ISSUE THREAD

**Issue by BigDataDaddy** [KeeTrayTOTP/KeeTrayTOTP#281]
I'm currently stuck on KeePass v2.41 and TrayTOTP V2.0.0.5 because it's the last KeePass version that supports TrayTOTP.  I'd love to upgrade to a current KeePass version and use KeeTrayTOTP.  After searching high and low though I can't find upgrade instructions that show a clear and safe path.  The KeePass software will upgrade, but it's an in place upgrade.  I can install the KeeTrayTOTP plugin into the new KeePass after that too.   However, I super uncomfortable doing it though because I can't find any place that assures me that I'll be in a working state with KeePass v2.42+ and KeeTrayTOTP after the upgrade and my current KeePass database version 2 files (*.kbdx) will all work as is, including the OTP generation with the seed metadata from TrayTOTP.  If I take the leap and it doesn't work my work env. is broken if not lost.  

Please help me identify an upgrade path!!!

**Comment by dannoe** [comment]
There is not really an "upgrade path". You can just install the newest version of KeePass and KeeTrayTOTP. As this "new" version originated from TrayTOTP, the name for the string field which the OTP seed is stored in should be the same: ``"TOTP Seed"`` (see screenshot below).

Just to be sure: Make a copy/backup of your database before opening it in the newest KeePass version.

![grafik](https://user-images.githubusercontent.com/7450586/199618365-8de5e044-8fb9-4c7a-9abf-fafbef78d774.png)

**Comment by BigDataDaddy** [comment]
Hi Dannoe, 

Thanks for responding.  Are your recommendations a "hypothetical should work" or is this a process that has been proven to work?

If anybody else has done an upgrade following this process, I'd sure appreciate you sharing your experience, esp. WRT to how well it worked or didn't, any deviation from the steps outlined, and any pitfalls.

Many thanks!

**Comment by robinvanpoppel** [comment]
The way @dannoe mentions is also how I would go about it. Create a backup of your .kdbx file and have an upgraded version Keepass with this version of the plugin ready and load up the copy. If you're able to generate TOTP codes you're good to go.

Good luck!

**Comment by BigDataDaddy** [comment]
Don't you think it's a little dismissive to close this issue without answering the question?  I understand that a contributor and a collaborator both with intimate understanding of KeeTrayTOTP have both described what their starting test case would be.  However that's very far from saying something that warrants closing the issue.  

Something a bit more direct, like "There is no tested upgrade process." or "Upgrades are not supported." or "We'll consider an upgrade feature in a future release." would have been more representative of the current situation and a bit more respectful of my question as a user.  I'd even have appreciated a "Test it yourself." response more that just being dismissed like this.

Sorry to be such a nag, but it's experiences like this that can tarnish the rep of OSS.

P.S. I fully intend to keep using KeePass, but I maybe looking for a new OTP plugin.

**Comment by dannoe** [comment]
I just tested it and it worked:

- I downloaded the old KeePass v2.41 and TrayTOTP V2.0.0.5.
- Created a new database and set up one password entry with TOTP.
- I closed the old keepass.
- I opened the new keepass with the previously created database.
- The entry still has TOTP set up and TOTP values are correctly generated.

You could have tested this in less time than I did, since I still had to search for the download of the old keepass+plugin.
