### ISSUE TITLE
Minor Typos in Help Window

### ISSUE THREAD

**Issue by BoffinBrain** [KeeTrayTOTP/KeeTrayTOTP#300]
I noticed a few small spelling/grammar mistakes when reading the help window. I would fork and make the corrections to `FormHelp.resx` myself, but it looks like there hasn't been any activity on GitHub for 2 years, so I don't know if someone would pull it. I'll leave the screenshots here.

![Typo1](https://user-images.githubusercontent.com/13255058/226161270-339d681b-28e9-488f-ac0c-05cae919851c.png)

it's -> its

![Typo2](https://user-images.githubusercontent.com/13255058/226161271-a19224b3-4a81-456d-ad52-ab80725dd56b.png)

show's -> shows
in case you required to used -> in case you're required to use

**Comment by robinvanpoppel** [comment]
@BoffinBrain, thanks! Regarding to the activity: : I personally am not using Keepass anymore (and thus this plugin). But if there are bugs I'm still accepting pull requests / issues and can do a new release. I can also pick this up myself.

**Comment by BoffinBrain** [comment]
Good to know. Thanks!
