### ISSUE TITLE
Add topics to this repository

### ISSUE THREAD

**Issue by dannoe** [KeeTrayTOTP/KeeTrayTOTP#64]
Add [Topics](https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) to this repository

Topic suggestions:
- keepass
- keepass-plugin

Example:
![grafik](https://user-images.githubusercontent.com/7450586/77895234-ff608380-7265-11ea-9e89-91b50b5e7481.png)

**Comment by robinvanpoppel** [comment]
I seem to be lacking the rights to do so. @victor-rds, are you able to add these topics?

**Comment by victor-rds** [comment]
@robinvanpoppel forgot to do this before transferring the repo! I lack the rights!

**Comment by robinvanpoppel** [comment]
@victor-rds, I've created a team of maintainers within the organization. Hopefully you have these rights now as well.

**Comment by robinvanpoppel** [comment]
@dannoe I've added these topics and one more.
