### ISSUE TITLE
Move this project to an organization

### ISSUE THREAD

**Issue by robinvanpoppel** [KeeTrayTOTP/KeeTrayTOTP#77]
@victor-rds, just opening this issue to explore the idea.

As this is currently a personal repository some things in this repository seem to be restricted to the owner only. A while ago @victor-rds mentioned [I hadn't time to look into this project, so is kinda abandoned](https://github.com/victor-rds/KeeTrayTOTP/issues/13#issuecomment-381461464) in #13. 

I was looking through the documentation and found this: `Repositories owned by an organization can grant more granular access.`. I do not have experience with organization accounts, but am hoping this would provide:
* Allowing more maintainers to manage this project. Things I've noticed is that it's not possible for maintainers in this repository to add/edit repository tags, or enable debug mode for github actions. There's probably more.
* Moving it to an organization could make it easier to identify that this is the maintained version.

My suggestion would be:
* Create an organization `KeeTrayTOTP`  (I did that to see if it was possible)
* Add @victor-rds, and other collaborators as members of this organization with appropriate rights
* Ask @victor-rds to move the repository to the organization / or fork it?
* Update the plugin to link to the new repository url (would this break by moving the repository? - otherwise maybe forking the project to the organization?)
* Update the readme.md in the root to clarify that this is the maintained version
* Update the link on the [Keepass plugins site](https://keepass.info/plugins.html).

Any pros or cons? What are your thoughts?

**Comment by alystair** [comment]
I think this is for the best as I've seen plenty great open source projects go unmaintained even though plenty of 3rd parties were submitting issues and PRs with no one to take care of them. Hope Victor agrees.

**Comment by dannoe** [comment]
>     * Ask @victor-rds to move the repository to the organization / or fork it?

>     * Update the plugin to link to the new repository url (would this break by moving the repository? - otherwise maybe forking the project to the organization?)

I think the correct steps should be:
- Fork repository to organization
- (Fork) Update returned UpdateUrl in KeeTrayTOTP_Plugin.cs to point to the new fork
- (Fork) Increase version number in AssemblyInfo.cs
- (Previous Repo) Change the version in the version_manifest to the new version of the fork.
- Inform Keepass Author about the change, so he can change the link on the official keepass plugin site. (maybe via the [Keepass forum](https://sourceforge.net/p/keepass/discussion/))

If we have enough active maintainers, we should increase the numbers of reviewers needed for a pull request to be accepted. It's still a plugin for a password manager, which should be controlled in terms of security.

**Comment by alystair** [comment]
When you do end up contacting the Keepass author - let him know to split KeeTrayTOTP into its own project as it's only linked through the defunct 'Tray TOTP' project... not ideal.

**Comment by victor-rds** [comment]
Hi everyone! Sorry I was asleep, just read this thread.

Yes I agree to move this project to an organization, I didn't realize tha @robinvanpoppel  would got this so far and for so long, should told you to fork instead.

This project was just me trying to solve a personal problem after the previous got abandoned, C# and .NET are not my main area of work, and for personal and professional reasons got my time and my will to continue.

I never used an Organization account and to be totally honest don't know what, that is if needed, should do, that said, please just explain the next steps.

**Comment by dannoe** [comment]
We shouldn't use a fork, we should use the github transfer function, so the issues will be keept.
@robinvanpoppel has to invite @victor-rds  to the organization to do so:
> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization. (from [Transferring a repository - GitHub Help](https://help.github.com/en/github/administering-a-repository/transferring-a-repository))

**Comment by victor-rds** [comment]
@dannoe When I mentioned the fork I was talking abou the past when I added @robinvanpoppel as a mantainer.

Also he already invited me, thanks for the docs link.

**Comment by alystair** [comment]
@robinvanpoppel although I won't likely maintain the codebase, I'm more than willing to help with minor housekeeping with sorting issues and act as a backup for 'no brainer' PRs.

Additionally, do you think we should renamed it to 'KeeTrayOTP' in case HMAC/HOTP is added via a future PR?

**Comment by dannoe** [comment]
> @dannoe When I mentioned the fork I was talking abou the past when I added @robinvanpoppel as a mantainer.

I was referring to the fork mentioned in https://github.com/victor-rds/KeeTrayTOTP/issues/77#issuecomment-609381868

**Comment by victor-rds** [comment]
@dannoe Sorry, I misread your comment

**Comment by victor-rds** [comment]
Done!

**Comment by robinvanpoppel** [comment]
> @robinvanpoppel although I won't likely maintain the codebase, I'm more than willing to help with minor housekeeping with sorting issues and act as a backup for 'no brainer' PRs.
> 
> Additionally, do you think we should renamed it to 'KeeTrayOTP' in case HMAC/HOTP is added via a future PR?

@alystair, thanks for the offering! I've added you, @victor-rds and @dannoe to a maintainers team within the organization. @victor-rds, thanks for your quick action and your previous work driving this plugin. I hope you continue to be involved :)

Regarding the name change to KeeTrayOTP, I'm thinking that we should hold that off as long as we do not have the support. Changing the name fully would also involve changing the name of the plgx file and warning users to delete the old file, next to the other changes as well. How do you feel about that?

**Comment by alystair** [comment]
Well, the reason I bring it up now is solely because we have to reach out to Keepass author to update URLs anyway. I'm unsure how the built-in update checker works.
