### ISSUE TITLE
config/help/about windows compressed and unreadable

### ISSUE THREAD

**Issue by r2evans** [KeeTrayTOTP/KeeTrayTOTP#8]
All of the KeeTrayTOTP-related windows appear to have too-small an inter-line spacing:

![keetraytotp-error2](https://cloud.githubusercontent.com/assets/5815808/20406100/d858b15e-acc0-11e6-8e0e-0a56c838fa11.png)

My system (surface book i7) is a hires system. This problem is true regardless of which monitor I show it on (monitor two is not hires). It may very well be related to win10 handling of windows in a mixed hires environment, though all other apps I use have not had a hires-related problem in at least 6 months.

My system: win10_64, KeePass 2.34, KeeTrayTOTP v0.9.6151.16981

**Comment by iyesin** [comment]
@r2evans hey. Are you still experiencing this issue?

**Comment by r2evans** [comment]
Yes, on both 0.9.0.2 and recently 0.9.1. (win10, keepass-2.38, surface book with its hires screen)

**Comment by Sanaki** [comment]
Can confirm the same issue on 125% DPI scaling (and 100%, but did not test with a full system restart) on a 1920x1080 display. Mine's less severe than the screenshot above.
![ktsquish](https://user-images.githubusercontent.com/1374333/39165099-427497e0-4772-11e8-8644-c19073396f3a.jpg)

**Comment by giwu37** [comment]
I can confirm that it looks like the screenshot of r2evans on my system (KeePass 2.40 portable, KeeTrayOTP 0.95, Windows 10, 3200x1800, 200% or 250% View)

**Comment by Swoy** [comment]
Hello, I'm also experiencing this issue. It looks like the image attached:

![20181104141032-settings - tray totp plugin](https://user-images.githubusercontent.com/5272077/47964538-e38a8b00-e03b-11e8-8cba-b7bb9eb396c3.png)


I'm on a 2560x1440 with 125% DPI scaling (but also on 100%)

**Comment by robinvanpoppel** [comment]
I am not able to reproduce this on my machine (Win10). In my keepass,exe,config I have this setting:
```xml
<appSettings>
    <add key="EnableWindowsFormsHighDpiAutoResizing" value="true" />
</appSettings>
```

Is anyone else experiencing this, and able to provide some means to resolve this?

**Comment by Sanaki** [comment]
I still don't have it via mono on Linux, but I had my girlfriend check and she still sees it on 0.99. I'll update with results after 0.101, but I doubt that will be different.

**Comment by Swoy** [comment]
This issue is no morefor me now after the last update.

**Comment by Sanaki** [comment]
Had my girlfriend update to 0.101, that line was already present in her keepass.exe.config, and the issue persists. If I can provide more info, I'd be happy to.

**Comment by dannoe** [comment]
I can reproduce this and will correct this in the future. We can probably copy some logic from keepass itself.

**Comment by avoidik** [comment]
I've had similar issue with DPI setting, the following registry tweak fixed it for me (this will disable DPI scaling awareness for the KeePass itself)

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\Program Files (x86)\\KeePass Password Safe 2\\KeePass.exe"="DPIUNAWARE"
```

**Comment by dannoe** [comment]
@avoidik Can you try it again?

**Comment by robinvanpoppel** [comment]
The latest development build can be found [here](https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases/tag/latest).
