### ISSUE TITLE
Use the correct way of providing menu items to keepass

### ISSUE THREAD

**Issue by dannoe** [KeeTrayTOTP/KeeTrayTOTP#90]
The correct way to provide menu items for the different places in keepass, is to return a single (root) ``ToolStripMenuItem`` in the ``GetMenuItem`` method. If you wan't to add more items, you should use a ``ToolStripDropDown`` as root and add children to it. see [Plugin Development (2.x) - KeePass](https://keepass.info/help/v2_dev/plg_index.html#co_menuitem)

> It was already done in the right click menu of entries (see #49).

Should we implement this with an option to enable the legacy method of providing menu items, as suggested in https://github.com/KeeTrayTOTP/KeeTrayTOTP/issues/61#issuecomment-606266999?

**Comment by robinvanpoppel** [comment]
I already chipped in on #6. I've experienced compatibility issues before, so I'd like to comply with the plugin development guidelines to prevent these as much as possible. 

Hopefully others will provide their opinion as well. How do you want to approach this @dannoe?
