### ISSUE TITLE
Update plgx prerequisites

### ISSUE THREAD

**Issue by dannoe** [KeeTrayTOTP/KeeTrayTOTP#99]
https://github.com/KeeTrayTOTP/KeeTrayTOTP/blob/650364b8d3c5cb5c076af9901314ca88b11a5135/KeeTrayTOTP/KeeTrayTOTP.csproj#L12

We have to increment this to 4.5. We use several things that are not included in the .NET Framework
3.5. Used for displaying a nicer error message to the user, if the required .net framework is not installed at plgx compilation time. 
see [Plugin Development (2.x) - KeePass](https://keepass.info/help/v2_dev/plg_index.html#plgx)

**Comment by Sanaki** [comment]
This may break mono builds. While I don't know the reason, mono seems to internally report an old version of .net despite being much more up to date.
Another project's fix when encountering this issue: https://github.com/dlech/KeeAgent/commit/c09f3dd775bfea6a3ae1b0a97aba37ba98744ae7

**Comment by robinvanpoppel** [comment]
That 3.5 feels wrong indeed. This is an area that I have not really explored myself. Would it be possible to bump to 4 at least? And maybe we can add specific github actions that build and test the plugin against mono to ensure compatiblity?
